### PR TITLE
Fixup: Updated to new stable 5.0.2. Check signatures.

### PR DESCRIPTION
**Pull request by ypid**
* See https://github.com/jchaney/owncloud/pull/12
* Removed commented out code.

### CODE REVIEW

**Comment by ypid** [comment]
@paulczar your current master still does not securely verify that the binary which is executed is the one supposed to be executed by the devs. Please fix this. Tor matters!

**Comment by paulczar** [comment]
Thanks @ypid I'll take a look at this over the next few days when I get a chance.

**Comment by ypid** [comment]
Thanks!

**Comment by paulczar** [comment]
signatures are now being checked in the master branch.

**Pull request closed without merging**
